/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BattleLogger__factory } from "./BattleLogger__factory";
export { FighterBrain__factory } from "./FighterBrain__factory";
