/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BattleLoggerInterface extends Interface {
  getFunction(nameOrSignature: "recordBattle"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "BattleRecorded"): EventFragment;

  encodeFunctionData(
    functionFragment: "recordBattle",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "recordBattle",
    data: BytesLike
  ): Result;
}

export namespace BattleRecordedEvent {
  export type InputTuple = [
    fighterA: BigNumberish,
    fighterB: BigNumberish,
    submitter: AddressLike,
    battleHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    fighterA: bigint,
    fighterB: bigint,
    submitter: string,
    battleHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    fighterA: bigint;
    fighterB: bigint;
    submitter: string;
    battleHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BattleLogger extends BaseContract {
  connect(runner?: ContractRunner | null): BattleLogger;
  waitForDeployment(): Promise<this>;

  interface: BattleLoggerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  recordBattle: TypedContractMethod<
    [fighterA: BigNumberish, fighterB: BigNumberish, battleHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "recordBattle"
  ): TypedContractMethod<
    [fighterA: BigNumberish, fighterB: BigNumberish, battleHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BattleRecorded"
  ): TypedContractEvent<
    BattleRecordedEvent.InputTuple,
    BattleRecordedEvent.OutputTuple,
    BattleRecordedEvent.OutputObject
  >;

  filters: {
    "BattleRecorded(uint256,uint256,address,bytes32,uint64)": TypedContractEvent<
      BattleRecordedEvent.InputTuple,
      BattleRecordedEvent.OutputTuple,
      BattleRecordedEvent.OutputObject
    >;
    BattleRecorded: TypedContractEvent<
      BattleRecordedEvent.InputTuple,
      BattleRecordedEvent.OutputTuple,
      BattleRecordedEvent.OutputObject
    >;
  };
}
